### ISSUE TITLE
MultiSite Access List is missing pagination, "never", and added by cloumn

### ISSUE THREAD

**Issue by jaydrogers** [521dimensions/wp-sandbox#28]
## Original Design
![03a2-multisiteaccess-wpsandbox](https://f.cloud.github.com/assets/3174134/2059471/a708ebec-8bb1-11e3-84d6-05cb0858f4a4.jpg)

## What is being displayed now
![screen shot 2014-02-01 at 8 26 31 pm](https://f.cloud.github.com/assets/3174134/2059472/bac6cfc8-8bb1-11e3-8937-c80ad5f61234.png)

## Items To Fix

1. This table is missing pagination and search
2. Never is displaying as 00-00-00 00:00:00
3. There needs to be an "added by" column here

**Comment by danpastori** [comment]
With the new designs in v1.0, this is different.
