### ISSUE TITLE
Error being created in Apache Logs

### ISSUE THREAD

**Issue by jaydrogers** [521dimensions/wp-sandbox#36]
I am getting the following error in the apache logs. 192.168.1.10 is an **not** an authenticated IP address:

`mod_fcgid: stderr: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE blog_id = '1'' at line 1 for query SELECT ip FROM wp_wps_coming_soon WHERE ip = '192.168.1.10' WHERE blog_id = '1' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WPSandbox->wps_check_valid_testing, WPSandbox->wps_check_valid_ip `

**Comment by danpastori** [comment]
This should be resolved.
